version: '3.5'

networks:
  jalnet:
    name: jalnet
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.42.0/24

services:
  memcached:
    image: memcached
    container_name: jalcache
    restart: always
    networks:
      - jalnet
    ports:
      - "11211:11211"