version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t jockbot_nhl .
      - run: docker run --rm --name jockbot jockbot_nhl

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
